# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f981a21546dcaaa8596f62cb5df75b0c7afbdab8edea6022d36f5bdb8291b2ce56f2bd033c5815e38a6902758b3b297e3c9f78949d51c8f94f7db32569cf054

test:
  secret_key_base: ce6992426211afe7524dcfa52ae3e7da91fb409029f09969a6a6065a10ce1baa79902d1992d11f1e63bd8f6d35aaf7aed5e26b8f6bad796f35bfc4ac086b2d09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
